/**
 * Docs site for docusaurus-plugin-llms, dogfooding edition: the site runs
 * docusaurus-plugin-llms against its own documentation, so the deployed site
 * serves a live llms.txt (+ llms-full.txt and markdown files) generated by
 * the plugin from ../docs.
 */
const config = {
  title: 'docusaurus-plugin-llms',
  tagline: 'LLM-friendly docs for your Docusaurus site',
  favicon: 'img/favicon.png',

  // Project pages on GitHub: https://rachfop.github.io/docusaurus-plugin-llms/
  url: 'https://rachfop.github.io',
  baseUrl: '/docusaurus-plugin-llms/',

  onBrokenLinks: 'throw',
  onBrokenMarkdownLinks: 'warn',

  i18n: {
    defaultLocale: 'en',
    locales: ['en'],
  },

  presets: [
    [
      'classic',
      {
        docs: {
          // Docs live at the repo root, shared with the README links; the
          // site reads them in place so there is a single source of truth.
          path: '../docs',
          sidebarPath: './sidebars.js',
          editUrl:
            'https://github.com/rachfop/docusaurus-plugin-llms/edit/main/docs',
        },
        blog: false,
        theme: {
          customCss: './src/css/custom.css',
        },
      },
    ],
  ],

  // Dogfood: this plugin generates the llms.txt for this very site at
  // https://rachfop.github.io/docusaurus-plugin-llms/llms.txt
  plugins: [
    [
      'docusaurus-plugin-llms',
      {
        // Docs live at the repo root (shared with the plugin's README); point
        // the plugin at them instead of the default siteDir/docs.
        docsDir: '../docs',
        generateMarkdownFiles: true,
      },
    ],
  ],

  themeConfig: {
    navbar: {
      title: 'docusaurus-plugin-llms',
      items: [
        {
          type: 'docSidebar',
          sidebarId: 'docs',
          position: 'left',
          label: 'Docs',
        },
        {
          href: 'https://github.com/rachfop/docusaurus-plugin-llms',
          label: 'GitHub',
          position: 'right',
        },
      ],
    },
    footer: {
      style: 'dark',
      links: [
        {
          title: 'Docs',
          items: [
            { label: 'Overview', to: '/docs/overview' },
            { label: 'Installation', to: '/docs/installation' },
            { label: 'Configuration', to: '/docs/configuration' },
          ],
        },
        {
          title: 'More',
          items: [
            {
              label: 'GitHub',
              href: 'https://github.com/rachfop/docusaurus-plugin-llms',
            },
            {
              label: 'llmstxt.org',
              href: 'https://llmstxt.org/',
            },
          ],
        },
      ],
      copyright: `Copyright © ${new Date().getFullYear()} Patrick Rachford. Built with Docusaurus.`,
    },
  },
};

module.exports = config;
